### ISSUE TITLE
how to run only single command in play ground

### ISSUE THREAD

**Issue by tharun-d** [mongodb-js/vscode#109]
Assume I have two queries in the playground. I am unable to run the individual query. If I click the run button it is running all queries. I want to select one query and run it

**Comment by Anemy** [comment]
Hi Tharun,

This is something we have planned :) Currently only running the entire playground is possible.

If you have more ideas or suggestions, we've got a feedback forum that's probably best suited for it: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code

Thanks for the trying out the extension - we'll be adding more features in the coming weeks & months.

**Comment by Anemy** [comment]
@tharun-d We've just added support in `0.1.0` to run partial playgrounds. You should be able to now see a button to run a code selection inside of a playground.

**Comment by tharun-d** [comment]
just verified its working cool.

but one thing i observed
1. 
use('hello');
db.tempCollection.find({status:"Qualified"}).count()
db.trainingcentre.find({status:"Qualified"}).count()

only last count is coming.

And also I don't want to use("hello") everytime
only once is that possible

**Comment by Anemy** [comment]
Ah something we're discussing is instead of including the explicit `use DB_NAME` command, having it so you are prompted for the db name when you want to run the playground. Looks like there are benefits to both approaches. Maybe if there is no db explicitly passed in the selection or playground we can prompt...


Currently the output of the playground is the output of the last command run. Not sure if this is something we plan to change, we will be looking into the output format of the playground soon though and it might get visited then.
