### ISSUE TITLE
Unable to find document with NumberLong id

### ISSUE THREAD

**Issue by arsmn** [mongodb-js/vscode#131]

**Comment by Anemy** [comment]
Could you describe the action you're doing?
Are you clicking on documents in the tree view with NumberLong ids? I'll give this a test.

**Comment by arsmn** [comment]
Yes when I click on documents with NumberLong id, this error happens

**Comment by Chronostasys** [comment]
I've got the same problem. In my case, I used a .Net Guid as _id field of my user collection, and when I clicked on documents it tells me "Unable to find document".    

--------
![image](https://user-images.githubusercontent.com/49905799/88354530-ceb3d500-cd93-11ea-9beb-55ee3c253606.png)  
document data  
![image](https://user-images.githubusercontent.com/49905799/88354588-f6a33880-cd93-11ea-86ac-1651cc31b810.png)  
![image](https://user-images.githubusercontent.com/49905799/88354598-03279100-cd94-11ea-8d64-2f0f36457a49.png)  
error after click

**Comment by Anemy** [comment]
Hi @arsmn we've released version `0.4.0` which has a fix for showing documents with numberlong ids as well as binary ids. I'm going to close this, feel free to reopen if when you update you still run into this issue. Thanks for reporting the issue and helping us improve the extension!
I think there still might be a slight display bug around number longs since javascript doesn't play too nicely with them, but it should be unrelated to this issue.

**Comment by arsmn** [comment]
Hi @Anemy
Thanks for the update, I checked that and it's fixed.
