### ISSUE TITLE
Feature Request - "Copy Document" option in context menu

### ISSUE THREAD

**Issue by jcgerhard** [mongodb-js/vscode#144]
## Feature Request

Having a "Copy Document" option in a documents' context menu

## Detailed Description

To get a more fluent way of working with a mongo instance, it would be nice to have this additional option in the mouse context menu of a document entry. Sometimes I need to duplicate documents to fill a collection with dummy data.
This feature would make it way more easy to do this.

## Context

I have been working with the extension solely for a few weeks now. I really love it beacause there is no need to left VS Code to work on a database anymore. I would like to replace my mongodb client completely with this extension.
This feature would make it way more comfortable to use while working the hole day with it.

## Possible Implementation

![mongo-vscode-document-copy](https://user-images.githubusercontent.com/29855366/86920352-f6ffca80-c129-11ea-9e5c-f2fa0ade44d4.jpg)

**Comment by Anemy** [comment]
@jcgerhard Thanks for the good suggestions! Happy to hear you're enjoying the extension and finding it useful. 

We're doing some improvements to the tree view currently (the next version will have indexes!). I'm not sure if we'll be touching the document context menus just yet, one of the reasons we aren't jumping on it yet is because it's a bit hard to infer which document you're interacting with just based on `_id`. Probably once we look into https://github.com/mongodb-js/vscode/issues/139 we can do this. 
🤔 Maybe we can also have a `Duplicate Document` option to make the flow you're looking for a bit smoother. 
We'll comment here once we've got something in progress or live. Thanks again.

**Comment by jcgerhard** [comment]
A `Duplicate Document` option would be really fine! I try to use the extension solely during the last weeks. It's really a pleasure to stay in VS Code all the time. I am collection all the things I personally missing and will report them here as issues. But: it's a great tool just yet! Please keep up the development! I could imagine a complete client replacement.

**Comment by Anemy** [comment]
Pr open from a community contributor! 🥳 
https://github.com/mongodb-js/vscode/pull/419

**Comment by Anemy** [comment]
This is released in the new `0.10.0` version. Thanks for opening the issue!
https://github.com/mongodb-js/vscode/releases

**Comment by jcgerhard** [comment]
That's great! I thought this project has died. I will test it. Keep up!
