### ISSUE TITLE
Option to save connection either as a Workspace or Globally via connections panel (and command palette)

### ISSUE THREAD

**Issue by MullinsN** [mongodb-js/vscode#260]
## Feature Request

If the user, does not take the option to save the connection at the time the connection is made, there seems to be no MongoDB command (CTRL+SHIFT+P) or context sensitive option in the connections panel to save the connection at later point (Currently using v0.4 extension) or any indicator that connection is not saved.

## Detailed Description

When initially using the connection string, I didn't notice (User error) the option to save connection globally or workspace, even though I had saved them previously, probably to distracted in getting the connection to work.

It would be good to have the option to save the connection in the connection panel.

Also a W or G preceding to indicate whether this is a Global or Workspace connection and a mini tick / x in a circle maybe for whether it is saved or not. Maybe a bit too much hand holding?

Question? Can a connection be moved from a workspace to a gobal connection save space?

## Context

Once I realized what I was doing it wrong it was a wee bit frustrating to not be able to fix within the connections panel or there was no MongoDB command from the command palette.

Again with a MongoDB+SRV it's not to bad to reconnect, but with a more advanced setting that may require some tinkering, then it would be frustrating.

**Comment by Anemy** [comment]
Hi @mullinsn I think the best UX is a bit hard to nail down, as you're maybe mentioning here. 

Initially we actually had it implemented so that when a new connection is created you are then prompted to choose where that connection is saved (workspace/globally/session). However, we found that to be a bit obtrusive to first time users and more simple use cases, so we decided to move those options to the settings and default to globally storing connections. I do agree that having a setting here isn't ideal, and it could be nice to be able to configure how a connection is stored into advanced settings in the connection form.

Probably the easiest way to transfer a connection, is as you mentioned, with copying the connection string. Down the line we'd like to look into editing stored connections. It's not something that's possible at the moment, but it is on our radar and feedback forum: https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code/suggestions/41971459-ability-to-edit-connections
If it's alright with you I'll close this issue, feel free to reopen. Thanks again for bringing this up and your other valuable feedback!
