### ISSUE TITLE
Feature Request: Copy collection schema, 

### ISSUE THREAD

**Issue by Rohan-ult** [mongodb-js/vscode#278]
## Detailed Description

Ability to copy collection schema, Export schema to a typescript file, 

## Context

So that we can use it (schema interface) for typescript. Basically It will infer types about collection. Example:
```ts
import { MongoClient } from "mongodb";
// import CollectionSchema interface generated by extension.
import type { CollectionSchema } from "../TestDemo.schema.ts"; 

async function main() {
    await mongoClient.connect();
    const collection = mongoClient.db("test").collection<CollectionSchema>('demo');
}
main().catch(console.log)
```

**Comment by mmarcon** [comment]
Hi @Rohan-ult, thank you for this suggestion. I see how that can be helpful during development. I submitted this as a feature request on your behalf in our [feedback portal](https://feedback.mongodb.com/forums/929236/suggestions/43285071) so it's easier for us to track and I am closing the issue here.
