### ISSUE TITLE
MongoDB output are not showing in PlayGround Output area but showing in a different pane called Playground Result.

### ISSUE THREAD

**Issue by JaySep** [mongodb-js/vscode#287]
![VSCODE_MONGO](https://user-images.githubusercontent.com/34396656/114721906-fb12e580-9d56-11eb-8889-63a3d844d3c4.jpg)
Why the output is not showing in the playground output area instead it is showing in this Playground Result area, which is a bit inconvenient.

**Comment by MullinsN** [comment]
Hello,

I think this was changed in version 0.3.0 to sent playground output to the editor.

[#198](https://github.com/mongodb-js/vscode/pull/198)

**Comment by alenakhineika** [comment]
Yes, we moved playground results from the output channel to the results pane in order to enable syntax highlighting and allow users to open editable documents directly from the playground results. The output channel is used now to print debug information from `console.log()` that you can use inside your playground scripts.
