### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Marveloos3WebD2** [mongodb-js/vscode#310]
#### Environment mongodb will  accept connect string 

- node.js / npm versions:
- OS:

**Comment by Marveloos3WebD2** [comment]
MongoDB for VSC is not accepting connection string.  Not able to paste connection , no action after pressing Enter after typing connection string on bar.  Not able to use MongoDB in VSC.

**Comment by Anemy** [comment]
Hi @Marveloos3WebD2 - thanks for reporting. I think this might be an issue with another extension in vscode capturing key actions so that vscode can't properly handle them. This isn't something our extension can control really.

Here's what my shortcuts for command+v look like (preferences->Keyboard shortcuts):
<img width="1158" alt="Screen Shot 2021-07-13 at 12 39 24 PM" src="https://user-images.githubusercontent.com/1791149/125499800-28a0ca85-baa9-4cfc-bc54-a3f8380a2205.png">
Are there more shortcuts registered in your vscode for pasting or hitting enter? Do you have other extensions installed?
I'm going to close this if that's alright, feel free to reopen.
