### ISSUE TITLE
Pass output to another command

### ISSUE THREAD

**Issue by htphuocdlBrtChip** [mongodb-js/vscode#335]
## Question

- [ ] Do we have feature to stored output result and put it to another command. Something like below:
```js
use('input-db');
const bulkData = db.getCollection('input-collection').aggregate([
{
    $project: {
      insertOne: {
        document: {
          field_1:        "value 1",
          // isSuccess:      false,
          // retry:          0,
        }
      }      
    }
  }
])

use('output');
// https://docs.mongodb.com/manual/reference/method/db.collection.bulkWrite/#mongodb-method-db.collection.bulkWrite
db.getCollection('output-db').bulkWrite(bulkData)
```
- [ ] Can't query with field: isSuccess, retry :(

**Comment by alenakhineika** [comment]
Hey, there are several things here:

- you are missing the`.toArray()` method after `aggregate`, to convert it to an actual array instead of a cursor returned by default.
-  to insert the bulk of documents please use the `insertMany` function: https://docs.mongodb.com/manual/reference/method/db.collection.insertMany/
- you messed up a little bit names of your db and collection, which may confuses you. You specified `db.getCollection('output-db')` but what you probably meant is `db.getCollection('output-collection')`.

So it will look like this:

```js
use('input-db');

const aggregation = [ ... ];
const bulkData = db['input-collection'].aggregate(aggregation).toArray();

use('output-db');

db['output-collection'].insertMany(bulkData);
```
