### ISSUE TITLE
Can't create connection after using special character in password

### ISSUE THREAD

**Issue by sefatanam** [mongodb-js/vscode#341]
#### Current Behavior 

I'm using mongodb with Docker. I can get access by using this connection string in Rider ``mongodb://mongoadmin:pass#word1@localhost:27017`` . I provided same connection string in this plugin to connect my mongodb database But got this error several time, didn't get any proper documentation or solution yet.
#### Additional Context/Screenshots
![asd](https://user-images.githubusercontent.com/37630292/129389130-2b011a6a-60e2-41c0-bc18-80024d48a983.png)

**Comment by Anemy** [comment]
Hi @sefatanam - when connecting with a connection string with a password that has special characters, you'll need to encode those characters so that it can be parsed successfully.

More information: https://docs.atlas.mongodb.com/troubleshoot-connection/#std-label-special-pass-characters

For instance, if your password is `p@ssw0rd'9'!` you'll need to pass it in a uri as `p%40ssw0rd%279%27%21`

Thanks for checking out the extension!

**Comment by sefatanam** [comment]
Thank you , now it works perfectly.

**Comment by thre3eye** [comment]
This doesn't seem to work (it works in other tools with the same encoded password).
