### ISSUE TITLE
Bug Report - PLAYGROUND DOESNT RETURN ANY DB DATA

### ISSUE THREAD

**Issue by Lucky-ta** [mongodb-js/vscode#413]
#### Current Behavior

The playground function doesnt recognize any data from my database when db is running on a docker container 

#### Expected Behavior/Code

Show all db results when it runs a query on Playground.

#### Environment

- OS:
- - Windows 10 [WSL2], Linux Ubuntu

- node.js / npm versions:
- - NODE VERSION: v16.14.2
- - NPM VERSION: 8.5.0

#### Additional Context/Screenshots

![mongoDbDebbug](https://user-images.githubusercontent.com/83483287/168669975-3c6babe3-b4d5-41a2-aaba-9a7fbb6eb71a.JPG)

![mongoDbDebbug2](https://user-images.githubusercontent.com/83483287/168670004-1475a98c-8272-4e38-a18e-991eccf20ece.JPG)

-- Db running on port 27017

![dbonport](https://user-images.githubusercontent.com/83483287/168670900-f4d8bbb1-7b78-4f68-90d2-07f0ada89c95.JPG)

**Comment by alenakhineika** [comment]
Hey, looking at your screenshots, it feels like you are executing not the whole playground, but single lines of the playground. On the first screenshot, I can see that the first line is highlighted and the playground result says that you switched to your preferable database. On the second screenshot, the second line is selected and you get the find operation result. If my assumption is correct, then the reason you get an empty array is because when you select only find without a use statement, then use statement in not being executed, it means that you haven't switched to your database and you are running the find command on the default `test` database, that does not have documents you are accessing and you get an empty result.

**Comment by Lucky-ta** [comment]
Hii, @alenakhineika! 
  Thank you for send me a feedback!
 Actually it works! When i select all code lines it returns me all the data from db.
I will close the Bug Report Issue, Thankssss!!

**Comment by alenakhineika** [comment]
Glad it worked for you! By the way, if you want all lines of the playground to be executed, you don't have to select anything. You can just click the play button at the top-right corner of the window and everything will be executed.
