### ISSUE TITLE
MongoDB Error: querySrv ENODATA

### ISSUE THREAD

**Issue by sharpenhead** [mongodb-js/vscode#502]
**INFO**
- _node.js version:_ v18.12.21
- _discord.js version:_ v14.7.1
- _mongoose version:_ v7.0.3

When doing **node .** in the terminal, sometimes I get this error, and it has been interfering with my Discord bot being able to start up and stay online.

Sometimes, it says loaded commands and events but does not say anything about the database being connected. When this happens, none of the Discord bot's commands are usable and I have to keep doing **node .** until it says database connection successful without showing the error (shown below).

Sometimes it shows the error and sometimes it does not. I recently deleted some files that used MongoDB, and ever since I did that, this error has been showing. I am sure I deleted all traces of the command(s) that were regarding the files I had deleted.

I've been stuck with this error for quite some time now, so any help would be greatly appreciated. Thank you.

```
Discord API Error: Error: querySrv ENODATA _mongodb._tcp.v14.awy9ngq.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:251:17) {      
  errno: undefined,
  code: 'ENODATA',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.v14.awy9ngq.mongodb.net'
}
```

**Side note:** I also get this error shown below:
```
Discord API Error: MongooseError: Model.findOne() no longer accepts a callback
```
I am not exactly sure if this issue is tied in with the problem that I mentioned above. This error occurs whenever I try and run any command from the Discord bot.

**Comment by Anemy** [comment]
@sharpenhead The MongoDB VSCode extension issue section is probably not the best place for this sort of question. The [MongoDB community forums](https://www.mongodb.com/community/forums/), [stack overflow](https://stackoverflow.com/), or other question answers forums are probably going to be a better place. 
I don't know about the connectivity issue. For the other one:
> ```Discord API Error: MongooseError: Model.findOne() no longer accepts a callback``` 

This looks like a possible issue around syntax and versioning - did you recently update the version of the [MongoDB node driver](https://www.mongodb.com/docs/drivers/node/current/)? Are you still using callbacks instead of the Promise async/await syntax?
