### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by guptagaurav89** [mongodb-js/vscode#510]
Adding connection not working on VS Code 1.77.1 on Windows NT x64 10.0.19045. getting below error, although it is working on another machine.
Extension version - v0.11.1
![image](https://user-images.githubusercontent.com/13122327/230932213-9ef0a30c-120c-4744-ab28-546ad5da056f.png)

**Comment by alenakhineika** [comment]
According to Microsoft: _You might get this error if you don’t have the IRPStackSize registry entry on the server set high enough. Try to_ 

When the available RAM is low or the program is not able to access enough memory, errors occur. Probably this can be fixed by a software update, system cleanup, or registry editing.
