### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by karthik-553** [mongodb-js/vscode#600]
#### Environment

- node.js / npm versions:
- OS:

#### Additional Context/Screenshots

Unable to connect: 2251904:error:10000438:SSL routines:OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR:..\..\third_party\boringssl\src\ssl\tls_record.cc:592:SSL alert number 80

**Comment by karthik-553** [comment]
how to resove this error

**Comment by alenakhineika** [comment]
Hey, looks like you have a network access issue that needs to be configured. This is not caused by the extension itself. Here is a similar conversation happening related to Compass: https://www.mongodb.com/community/forums/t/error-while-connecting-my-database-through-mongodb-compass/243317. Feel free to reply to the same thread of the community forum or open a new one.
