### ISSUE TITLE
Feature Request: Use NodeJS driver

### ISSUE THREAD

**Issue by DutchMarcel** [mongodb-js/vscode#865]
## Detailed Description
Possibility to switch MongoDB drivers to be able to create/debug scripts locally in the same syntax as the tool that will eventually execute these scripts. In my case I would like to use the NodeJS driver.

## Context

I'm not sure what driver is used by this extension, but our deployment tool, which I have no control over, seems to use the NodeJS driver. Example syntax: db.collection('mycollection').findOne... and supports async/await structures.

The VSCode extension fails on these syntax differences. This makes it difficult to create and debug scripts, because you always need to transform your script from and back to the NodeJS syntax, which makes it an error prone process.

## Possible Implementation

If possible, add a switch somewhere to choose the preferred driver.

**Comment by nirinchev** [comment]
Hey @DutchMarcel, thanks for this suggestion - it's reasonable and something we've considered in the past but decided against it due to the complexities of adapting driver API changes (especially breaking changes) without negatively impacting users of mongosh/vscode extension. It's also reasonably straightforward to create a new js file, import the NodeJS driver and write a script, so we felt the value we'd provide there wouldn't be that high.

That being said, I can definitely see the convenience of having a transient playground to iterate on a query before pasting it back into your project and if there's sufficient demand from our users, we'll definitely revisit it. Might I suggest that you file a feature request on [our UserVoice page](https://feedback.mongodb.com/forums/929236-mongodb-for-vs-code) as that'll improve its visibility and allow other users of the vscode extension with similar needs upvote and comment on it.
